name: uRide-Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Remote Server to Known Hosts
        run: |
          ssh-keyscan -H 209.38.99.234 >> ~/.ssh/known_hosts

      - name: Pull Latest Changes and Reload PM2
        run: |
          ssh -o StrictHostKeyChecking=no princedeploy@209.38.99.234 << 'EOF'
            cd /home/princedeploy/_uRide_Backend
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            pm2 reload all
          EOF

      - name: Slack Notification - Deployment Success
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ success() }}
        env:
          SLACK_COLOR: good
          SLACK_MESSAGE: "Deployment Completed Successfully :rocket: commit: ${{ github.event.head_commit.message }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification - Deployment Failed
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ failure() }}
        env:
          SLACK_COLOR: danger
          SLACK_MESSAGE: "Failed deployment :x: commit: ${{ github.event.head_commit.message }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
